//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMakaan.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int cityId { get; set; }
        public string cityName { get; set; }
        public string cityImagePath { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string cityDesc { get; set; }
    }
}
